export default function Head() {
  return (
    <>
      <title>StichtingImedi</title> {/* your site title */}
      <link rel="icon" href="/favicon.ico" />
      <meta name="description" content="Generated by create next app" />
    </>
  );
}
