export default function Head() {
  return (
    <>
      <title>StichtingImedi</title>
      <link rel="icon" href="/logo.png" />
      <meta name="description" content="Generated by create next app" />
    </>
  );
}
